name: vfx_sheet
description: "On-set VFX Sheet"
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.3.6
  drift: ^2.13.0
  intl: ^0.20.2
  json_annotation: ^4.8.1
  printing: ^5.12.0
  csv: ^5.0.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.7.0
  flutter_lints: ^2.0.0
  drift_dev: ^2.13.0
