name: Deploy Flutter Web to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: gh-pages-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - run: flutter create . --platforms=web

      - name: Set BASE_HREF
        run: |
          REPO="${{ github.event.repository.name }}"
          if [[ "$REPO" == *.github.io ]]; then
            echo "BASE_HREF=/" >> $GITHUB_ENV
          else
            echo "BASE_HREF=/$REPO/" >> $GITHUB_ENV
          fi

      - run: flutter build web --release --base-href "$BASE_HREF" --dart-define=WEB_BUILD=true
      - run: cp build/web/index.html build/web/404.html

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/web
          force_orphan: true
          # voliteľne:
          # user_name: github-actions[bot]
          # user_email: 41898282+github-actions[bot]@users.noreply.github.com
