name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      # Optional: linting and tests
      # - run: flutter analyze
      # - run: flutter test

      # Configure for web if not yet configured
      - run: flutter create . --platforms=web

      - id: set-base-href
        run: |
          REPO_NAME=${{ github.event.repository.name }}
          if [[ "$REPO_NAME" == *.github.io ]]; then
            echo "BASE_HREF=/" >> $GITHUB_ENV
          else
            echo "BASE_HREF=/$REPO_NAME/" >> $GITHUB_ENV
          fi

      - run: flutter build web --release --base-href "$BASE_HREF" --dart-define=WEB_BUILD=true

      - run: cp build/web/index.html build/web/404.html

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
